import Head from 'next/head'
import styles from '../styles/Home.module.css'
import products from '../products.json'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
          <link rel="preconnect" href="https://app.snipcart.com" />
          <link rel="preconnect" href="https://cdn.snipcart.com" />
          <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.css" />
          <title>Card Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>Welcome to Goatland</a>
        </h1>

        <p className={styles.description}>
          Shop cards, collectables, and memorabilia.
        </p>

        <div className={styles.grid}>
            {products.map(product => {
                return (
                    <div key={product.id} className={styles.card}>
                        <img src={ product.image } alt={`Preview of ${product.title}`} />
                        <p>{ product.title}</p>
                        <p>{ product.description }</p>
                        <p> ${ product.price } </p>
                        <p>
                            <button className="snipcart-add-item"
                                    data-item-id={product.id}
                                    data-item-image={product.image}
                                    data-item-name={product.title}
                                    data-item-price={product.price}
                            >
                                Add to Cart
                            </button>
                        </p>
                    </div>
                );
            })}
        </div>
      </main>

      <footer className={styles.footer}>
          <script async src="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.js" />
          <div hidden id="snipcart" data-api-key="ZWUwN2UxNmItZjBkNy00NjM5LTlkZTgtZGFmYjgxZTZkZTEzNjM3ODMyNjY5MDQzOTM2NzQx" />
        <a>
          &copy; JONATHAN GREEN 2022
        </a>
      </footer>
    </div>
  )
}
